qimport React from "react";
import ReactDOM from "react-dom";
import "./index.css";
import App from "./App";
import registerServiceWorker from "./registerServiceWorker";
console..log('22222');
console.log('11111');
console.log("zzz");
console.log("fix bug");
ReactDOM.render(<App />, document.getElementById("root"));
registerServiceWorker();
